services:
  postgres:
    image: 'postgres:latest'
    container_name: MovieDB
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=secret
      # Porten vi kör på och vilken den speglas lokalt (ifall vi vill se det i typ pgAdmin)
    ports:
      - '5432:5432'
      # Ett sätt att spara datan mellan sessions.
      # Det som sparas är då Schema, tabellinnehåll, metadata och transaktionsloggar.
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Hade skapats (deklareras) utan denna raden men ger tillgång till saker som
# docker-compose down/up 
# Kan även lätt hitta och hantera volymen med.
# docker volume inspect <name>
# docker volume rm postgres-data
volumes:
  postgres-data: